// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjeVbK9QJwnjMC69vsseYqonWGBzExHDQ',
    appId: '1:174945449891:web:32a937018141eacdab0c16',
    messagingSenderId: '174945449891',
    projectId: 'chat-app-8eeff',
    authDomain: 'chat-app-8eeff.firebaseapp.com',
    storageBucket: 'chat-app-8eeff.firebasestorage.app',
    measurementId: 'G-40PBJPFF3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWMTFsSapr2r0amTKDzWcu5sMTGqXPpXE',
    appId: '1:174945449891:android:f7c993cde97ae652ab0c16',
    messagingSenderId: '174945449891',
    projectId: 'chat-app-8eeff',
    storageBucket: 'chat-app-8eeff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD41rgZLKMZi7wbcGYN_Db-09cK1zLZ-gw',
    appId: '1:174945449891:ios:799b32d6721a4ed1ab0c16',
    messagingSenderId: '174945449891',
    projectId: 'chat-app-8eeff',
    storageBucket: 'chat-app-8eeff.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD41rgZLKMZi7wbcGYN_Db-09cK1zLZ-gw',
    appId: '1:174945449891:ios:799b32d6721a4ed1ab0c16',
    messagingSenderId: '174945449891',
    projectId: 'chat-app-8eeff',
    storageBucket: 'chat-app-8eeff.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjeVbK9QJwnjMC69vsseYqonWGBzExHDQ',
    appId: '1:174945449891:web:a5ce102b9e58d32bab0c16',
    messagingSenderId: '174945449891',
    projectId: 'chat-app-8eeff',
    authDomain: 'chat-app-8eeff.firebaseapp.com',
    storageBucket: 'chat-app-8eeff.firebasestorage.app',
    measurementId: 'G-K1DYHPQNVZ',
  );
}
